### ISSUE TITLE
Implement spell checker using symspell

### ISSUE THREAD

**Issue by dingchaoz** [dingchaoz/bookshelf#7]
After research and experiment with a few packages: pyspellchecker, autocorrect, nltk,
symspellpy seems to be the fastest one: 
https://github.com/mammothb/symspellpy
Need to create a function to use symspellpy to correct extracted texts.

**Comment by dingchaoz** [comment]
Another potential spell checker is to implement our own spellchecker using Levenshtein distance which computes the number of single character deletions, insertions, or substitution to convert from one string to the other, plus an use of an [English word dictionary](https://github.com/dwyl/english-words), efficiency is the name of game if we go down this route.

**Comment by shhudspeth** [comment]
Need to filter and clean text gleaned from book spines then run through spell checker. 

Also need to find a proper names corpus to check for author names

**Comment by dingchaozhang-tc** [comment]
Done
